[package]
name = "wingfoil-python"
version = "0.1.10"
authors = ["wingfoil@wingfoil.io"]
edition = "2024"
publish = ["wingfoil", "crates-io"]
license = "Apache-2.0"
keywords = ["graph", "stream", "dag", "trading", "python"]
homepage = "https://github.com/wingfoil-io/wingfoil/wingfoil-python"
documentation = "https://docs.rs/wingfoil-python"
description = "python bindings for wingfoil - graph based stream processing framework"

[lib]
name = "wingfoil"
crate-type = ["cdylib"]

[dependencies]

# parent
wingfoil = { path = "../wingfoil" }

# workspace deps
anyhow = {workspace = true}
chrono = {workspace = true}
derive_more = {workspace = true}
env_logger = {workspace = true}
lazy_static = {workspace = true}
log = {workspace = true}

# local deps
pyo3 = { version = "0.27", features = ["extension-module", "serde"] }


[package.metadata.maturin]
name = "wingfoil"

