[features]
default = ["async"]
full = ["async", "csv", "websockets", "kdb"]
kdb-integration-test = ["kdb"]
async = ["dep:tokio", "dep:futures", "dep:async-stream", "dep:futures-util", "tokio/time"]
csv = ["dep:csv"]
websockets = ["dep:tokio-tungstenite", "dep:tungstenite", "async", "tokio/net", "tokio/time", "tokio/macros"]
kdb = ["dep:kdb-plus-fixed", "async"]

[package]
name = "wingfoil"
version = "2.1.0"
authors = ["wingfoil@wingfoil.io"]
edition = "2024"
publish = ["wingfoil", "crates-io"]
license = "Apache-2.0"
keywords = ["graph", "stream", "dag", "hft", "trading"]
homepage = "https://github.com/wingfoil-io/wingfoil/"
documentation = "https://docs.rs/wingfoil"
description = "graph based stream processing framework"

[lib]
name="wingfoil"

[package.metadata.docs.rs]
scrape-examples = true

[dependencies]

# workspace
chrono = {workspace=true}
derive_more = {workspace=true}
env_logger = {workspace=true}
log = {workspace=true}
lazy_static = {workspace=true}


# project
priority-queue = "2.7.0"
itertools = "0.14.0"
num = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam = "0.8.4"
lobster = "0.7.0"
num-traits = "0.2"
derive-new = "0.7"
serde-aux = "4.7.0"
smallvec = "1.15.1"
rand = "0.9.2"
tynm = "0.2.0"
kanal = "0.1.1"
scopeguard = "1.2.0"
strum = {version = "0.27.2", features = ["derive"]}
strum_macros = "0.27.2"
formato = "0.3.0"
once_cell = "1.21.3"
anyhow = "1.0.100"
tinyvec = { version = "1.10.0", features = ["alloc"] }
arrayvec = { version = "0.7", features = ["serde"] }
criterion = { version = "0.8.1" }
quanta = "0.9.3"
ordered-float = "4.5.0"

# optional deps gated by feature flags
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
futures = { version = "0.3", optional = true }
async-stream = { version = "0.3.6", optional = true }
futures-util = { version = "0.3.31", optional = true }
csv = { version = "1.4", optional = true }
tungstenite = { version = "0.14.0", features = ["rustls-tls"], optional = true }
tokio-tungstenite = { version = "0.27.0", features = ["native-tls", "stream", "connect"], optional = true }
kdb-plus-fixed = { version = "0.4.1", features = ["ipc"], optional = true }




[dev-dependencies]

[[example]]
name = "async"
required-features = ["async"]

[[example]]
name = "order_book"
required-features = ["csv"]

[[example]]
name = "kdb"
required-features = ["kdb"]

[[example]]
name = "rfq"
required-features = ["websockets"]

[[bench]]
name = "graph"
harness = false

[[bench]]
name = "nanotime"
harness = false
