[package]
name = "wingfoil"
version = "0.1.14"
authors = ["wingfoil@wingfoil.io"]
edition = "2024"
publish = ["wingfoil", "crates-io"]
license = "Apache-2.0"
keywords = ["graph", "stream", "dag", "hft", "trading"]
homepage = "https://github.com/wingfoil-io/wingfoil/"
documentation = "https://docs.rs/wingfoil"
description = "graph based stream processing framework"

[lib]
name="wingfoil"

[package.metadata.docs.rs]
scrape-examples = true

[dependencies]

# workspace
chrono = {workspace=true}
derive_more = {workspace=true}
env_logger = {workspace=true}
log = {workspace=true}
lazy_static = {workspace=true}


# local
priority-queue = "1.2.0"
itertools = "0.10.1"
num = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam = "0.8.1"
lobster = "0.7.0"
csv = "1.1"
num-traits = "0.2"
derive-new = "0.7"
serde-aux = "3.0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tungstenite = { version="0.14.0", features = ["rustls-tls"]}
smallvec = "1.10.0"
rand = "0.8.5"

tynm = "0.1.7"
kanal = "0.1.1"
scopeguard = "1.2.0"
strum = {version = "0.27.1", features = ["derive"]}
strum_macros = "0.27.1"
async-stream = "0.3.6"
formato = "0.3.0"
once_cell = "1.21.3"
tokio-tungstenite = {version="0.27.0", features=["native-tls", "stream", "connect"]}
futures-util = "0.3.31"
anyhow = "1.0.98"
tinyvec = { version = "1.9.0", features = ["alloc"] }
arrayvec = { version = "0.7", features = ["serde"] }
criterion = {version = "0.7.0", features = ["async_tokio"]}
quanta = "0.9.0"


[dev-dependencies]


[[bench]]
name = "graph"
harness = false

[[bench]]
name = "nanotime"
harness = false
