name: Manual Auto Format and Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: '${{ github.ref_name }}'

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.branch }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Run cargo build
        run: cargo build --verbose

      - name: Commit and Push Formatted Changes
        if: success()
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "fmt"
            git push origin ${{ github.event.inputs.branch }}
          fi
