name: PyPI Publish

on:
  workflow_dispatch:
    inputs:
      pypi-target:
        description: 'Choose PyPI target'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel
        run: |
          cd wingfoil-python
          maturin --version
          maturin build --verbose --release --strip -o wheelhouse

      - name: List built wheels
        run: |
          cd wingfoil-python
          ls -lh wheelhouse

      - name: Set PyPI target
        id: pypi
        run: |
          if [ "${{ github.event.inputs.pypi-target }}" = "prod" ]; then
            echo "REPO_URL=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
            echo "TOKEN_NAME=PROD_PYPI_API_TOKEN" >> $GITHUB_ENV
          else
            echo "REPO_URL=https://test.pypi.org/legacy/" >> $GITHUB_ENV
            echo "TOKEN_NAME=TEST_PYPI_API_TOKEN" >> $GITHUB_ENV
          fi

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: wingfoil-python/wheelhouse
          repository-url: ${{ env.REPO_URL }}
          verbose: true
          user: __token__
          password: ${{ secrets[env.TOKEN_NAME] }}
