name: CI

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:      

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  ci:
    name: Build, Test, & Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Cache Rust Build Artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install clippy-sarif
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: clippy-sarif

      - name: Install sarif-fmt
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: sarif-fmt

      - name: Install grcov
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: grcov

      - name: Build
        run: cargo build --verbose

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --no-capture
        env:
          RUST_LOG: INFO
          
      - name: Run rustfmt
        run: |
          cargo fmt --all -- --check

      - name: Run rust-clippy
        run: |
          set -o pipefail
          set -e

          # First run Clippy with -D warnings to fail on any warnings
          cargo clippy --all-features -- -D warnings

          # Then run it again with JSON output for SARIF reporting
          cargo clippy --all-features --message-format=json \
            | clippy-sarif \
            | tee rust-clippy-results.sarif \
            | sarif-fmt

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
